spring:
  application:
    name: gateway
  profiles:
    default: oauth2 #eureka-off, eureka-on, oauth2

server:
  port: 4040

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka/


