spring.application.name=university-crud
spring.datasource.url=jdbc:postgresql://localhost:5433/education
spring.datasource.username=serviceeducation
spring.datasource.password=admin123
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate

#nombre del microservicio :/university_crud
server.servlet.context-path=/university_crud
#server port static=8081; server.port = 0 (dynamic)
server.port=8081