spring:
  datasource:
    hikari:
      connection-timeout: '20000'
      maximum-pool-size: '5'
    password: admin123
    username: serviceeducation
    url: jdbc:postgresql://localhost:5433/education
  application:
    name: university-crud
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: 'true'
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        SQL: DEBUG
server:
  servlet:
    context-path: /university_crud
  port: '0' #puerto estatico 8081, puerto dinamico = 0
eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka/
